default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "24.4.0"
    hooks:
      - id: black
        args:
          - --line-length=160
          - --include='\.py'
        stages: [commit, manual]
        types: [python]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        stages: [commit, manual]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.4.1"
    hooks:
      - id: ruff
        args:
          - --line-length=160
          - --select=PL,A,ARG,ASYNC,E,F,B003,B006,B007,C901,N,PLR1711,PLR2004,RUF100,INP001
          #- --ignore=F722,PLW0603,PLR0913,PLR0912,PLC1901,PLW2901,PLR0915,PLR5501,PLR0402,PLR0911,PLW0602,PLE1205,PLR1711,PLR0133
        stages: [commit, manual]