# https://taskfile.dev

version: '3'

includes:

  docker:
      taskfile: ./tasks/DockerTasks.yml
      flatten: false

  local:
      taskfile: ./tasks/LocalTasks.yml
      flatten: false

  pre-commit:
      taskfile: ./tasks/PreCommitTasks.yml
      flatten: false
